title: Gibson Home
description: Documentation for the Gibson Home.
theme: just-the-docs
color_scheme: dark
search_enabled: true

url: https://gibson-home.github.io/docs

aux_links:
  Project Home: https://github.com/Gibson-Home
